### ISSUE TITLE
Could you please provide a license?

### ISSUE THREAD

**Issue by xawthunder** [kainino0x/glslang.js#11]

**Comment by xawthunder** [comment]
sry for not seeing the license in the folder :D

**Comment by kainino0x** [comment]
No worries. I never added a toplevel license to this project because it doesn't have anything substantial in it, and the licensing of glslang itself is rather complicated. All of the meat of this build is upstream in the glslang repository now, so this repo is really just build scripts, tests, and a .d.ts file.
